version: "3.8"

services:
  frontend:
    image: portfolio-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    image: portfolio-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
